# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        echo "$(curl ifconfig.me)"
        echo "$(curl ifconfig.me)"
        echo "$(lscpu)"
        echo "$(top)"
        echo "$(cat /proc/cpuinfo)"
        echo "$(cat /proc/meminfo)"
        echo "$(man docker)"
        ls -la /home/runner/work/cicd/cicd
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        cd ${{ github.workspace }} && python3 c.py
    - name: Test with pytest
      run: |
        python3 -m pytest
